auth:
  quick-login:
    file-path: personal-metadata-credentials.json

aws:
  region: eu-central-1
  account-id: 844933496707
  cognito:
    user-pool-id: eu-central-1_S5NuJmFiM
    user-pool-client-id: 18aqnadaa85qoj62ulkiqagfdu
    identity-pool-id: eu-central-1:9401cab2-e1d1-4272-a04e-d4892b5a0201
  dynamodb:
    metadata-table-name: personal-metadata-eu-central-1-table
    created-at-index-name: CreatedAtIndex

metadata:
  recommended: Title|Time|Location

logging:
  level:
    root: INFO
    software.amazon.awssdk: INFO